
package pl.edu.pjwstk.tpr.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonSearch", targetNamespace = "http://search/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonSearch {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<pl.edu.pjwstk.tpr.jaxws.client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchForPeople", targetNamespace = "http://search/", className = "pl.edu.pjwstk.tpr.jaxws.client.SearchForPeople")
    @ResponseWrapper(localName = "searchForPeopleResponse", targetNamespace = "http://search/", className = "pl.edu.pjwstk.tpr.jaxws.client.SearchForPeopleResponse")
    @Action(input = "http://search/PersonSearch/searchForPeopleRequest", output = "http://search/PersonSearch/searchForPeopleResponse")
    public List<Person> searchForPeople(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchQuery arg0);

}
